'use client';

import {useEffect, useState} from 'react';
import Link from 'next/link';
import {Files, Clock, CheckCircle, AlertTriangle, XCircle, RefreshCw} from 'lucide-react';
import {api} from '../../lib/api';
import StatCard from '../../components/dashboard/StatCard';
import {Loader, Empty, ErrorMessage, StatusBadge} from '../../components/common/UI';

export default function UserDashboard() {
  const [stats, setStats] = useState(null); const [rows, setRows] = useState([]); const [notifications, setNotifications] = useState([]); const [error, setError] = useState('');
  useEffect(() => { Promise.all([api.userDashboard(), api.userSubmissions(), api.notifications()]).then(([dashboard, submissions, notices]) => { setStats(dashboard); setRows(submissions.slice(0, 5)); setNotifications(notices.slice(0, 3)); }).catch(loadError => setError(loadError.message)); }, []);
  if (!stats) return <Loader/>;
  return <><div className="page-title"><div><div className="eyebrow">MY RECORDS</div><h2>Land record overview</h2><p>Track your submitted records throughout review and verification.</p></div><Link className="button" href="/user/upload">Upload land record</Link></div><ErrorMessage>{error}</ErrorMessage><div className="stat-grid"><StatCard label="Total Submitted" value={stats.total_submitted} icon={Files} href="/user/submissions"/><StatCard label="Pending" value={stats.pending_review} icon={Clock} tone="amber" href="/user/submissions?status=SUBMITTED"/><StatCard label="Processing" value={stats.processing || 0} icon={RefreshCw} href="/user/submissions?status=PROCESSING"/><StatCard label="Verified" value={stats.verified} icon={CheckCircle} tone="green" href="/user/submissions?status=VERIFIED"/><StatCard label="Needs Review" value={stats.needs_review} icon={AlertTriangle} tone="amber" href="/user/submissions?status=NEEDS_REVIEW"/><StatCard label="Rejected" value={stats.rejected} icon={XCircle} tone="red" href="/user/submissions?status=REJECTED"/></div>{notifications.length > 0 && <section className="card" style={{marginTop:20}}><div className="section-head"><div><div className="eyebrow">NOTIFICATIONS</div><h3>Record notices</h3></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>NOTICE</th><th>DATE</th></tr></thead><tbody>{notifications.map(notice => <tr key={notice.id}><td><b>{notice.title}</b><br/><small>{notice.message}</small></td><td>{new Date(notice.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div></section>}<section className="card" style={{marginTop:20}}><div className="section-head"><div><h3>Recent submissions</h3><p>Live records from your account.</p></div><Link href="/user/submissions">View all</Link></div>{rows.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>SUBMISSION</th><th>DOCUMENT</th><th>STATUS</th><th>SUBMITTED</th><th>DETAIL</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>#{row.id}</td><td>{row.document?.original_filename || 'Land record'}</td><td><StatusBadge status={row.status}/></td><td>{new Date(row.submitted_at).toLocaleDateString()}</td><td>{row.status === 'REJECTED' ? <span className="rejection-detail">{row.rejection?.reason_category || 'Reason unavailable'}</span> : '—'}</td></tr>)}</tbody></table></div> : <Empty title="No submissions yet" text="Upload a scanned land record to begin AI-assisted verification."/>}</section></>;
}
