'use client';

import {useEffect, useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowRight, LockKeyhole, MapPinned} from 'lucide-react';
import {API_URL, api} from '../../lib/api';
import {saveUser} from '../../lib/auth';
import {Button, ErrorMessage} from '../../components/common/UI';
import './login.css';

export default function Login() {
  const [role, setRole] = useState('user'); const [phone, setPhone] = useState(''); const [otp, setOtp] = useState('');
  const [delivery, setDelivery] = useState(null); const [officerId, setOfficerId] = useState(''); const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const router = useRouter();
  useEffect(() => { if (new URLSearchParams(window.location.search).get('google_success')) api.me().then(me => { saveUser(me); router.replace('/user/profile'); }).catch(() => setError('Google sign-in could not be completed.')); }, [router]);
  async function sendOtp() { setLoading(true); setError(''); try { setDelivery(await api.requestPhoneOtp(phone)); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  async function verifyOtp() { setLoading(true); setError(''); try { const result = await api.verifyPhoneOtp(phone, otp); saveUser(result.user); router.push(result.profile_completed ? '/user' : '/user/profile'); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  async function officerLogin(event) { event.preventDefault(); setLoading(true); setError(''); try { const result = await api.login({officer_id: officerId, password, role: 'officer'}); saveUser(result.user); router.push('/officer'); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  return <main className="login-page cadastral-login"><header className="login-branding"><div className="logo-line"><span className="logo-mark"><MapPinned size={22}/></span><b>Bhumi<span>AI</span></b></div><p className="initiative-line">Secure access for reliable land-record digitization.</p></header><section className="login-form-wrap"><div className="login-card"><div className="login-card-heading"><div className="eyebrow"><LockKeyhole size={13}/> SECURE ACCESS</div><h1>{role === 'user' ? 'Welcome to BhumiAI' : 'Government Officer Access'}</h1><p>{role === 'user' ? 'Phone verification is the primary record-submitter sign-in method.' : 'Use credentials issued by the authorized government administrator.'}</p></div><div className="login-field"><label>Workspace</label><select value={role} onChange={event => {setRole(event.target.value); setError('');}}><option value="user">Record Submitter</option><option value="officer">Verification Officer</option></select></div>{role === 'user' ? <><div className="login-field"><label>Indian mobile number</label><input value={phone} onChange={event => setPhone(event.target.value)} placeholder="9876543210 or +919876543210" inputMode="tel" disabled={Boolean(delivery)} required/></div>{delivery ? <><p className="auth-context">Verification code for <b>{phone}</b>. {delivery.delivery === 'development' ? 'Development OTP generated — no SMS was sent.' : ''}</p>{delivery.development_otp && <p className="login-success">Development code: <b>{delivery.development_otp}</b></p>}<div className="login-field"><label>6-digit verification code</label><input value={otp} onChange={event => setOtp(event.target.value.replace(/\D/g, '').slice(0, 6))} inputMode="numeric" maxLength={6} placeholder="123456"/></div><Button onClick={verifyOtp} loading={loading} loadingText="Checking code…" disabled={otp.length !== 6}>Verify & Continue <ArrowRight size={17}/></Button><button className="auth-context" type="button" onClick={() => {setDelivery(null);setOtp('');}}>Change phone number</button></> : <Button onClick={sendOtp} loading={loading} loadingText="Sending code…" disabled={!phone}>Send OTP <ArrowRight size={17}/></Button>}<div className="google-divider"><span>or</span></div><button className="google-auth-button" type="button" onClick={() => window.location.assign(`${API_URL}/api/auth/google/start`)}><span className="google-g">G</span>Continue with Google (legacy/linking)</button></> : <form onSubmit={officerLogin}><div className="login-field"><label>Government Officer ID</label><input value={officerId} onChange={event => setOfficerId(event.target.value)} required/></div><div className="login-field"><label>Issued Password</label><input type="password" value={password} onChange={event => setPassword(event.target.value)} required/></div><Button loading={loading} loadingText="Signing in…">Enter Officer Workspace <ArrowRight size={17}/></Button></form>}<ErrorMessage>{error}</ErrorMessage></div></section></main>;
}
