'use client';

import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {CheckCircle2, FileImage, FileText, Search, Send, UploadCloud, X} from 'lucide-react';
import {request} from '../../../lib/api';
import {Button, ErrorMessage, Toast} from '../../../components/common/UI';

function Journey({uploaded}) { return <ol className="citizen-journey" aria-label="Submission journey"><li className="current"><span>1</span><b>Select document</b></li><li className={uploaded ? 'complete' : ''}><span>{uploaded ? <CheckCircle2 size={14}/> : '2'}</span><b>Upload</b></li><li><span>3</span><b>Processing</b></li><li><span>4</span><b>Officer review</b></li><li><span>5</span><b>Verified record</b></li></ol>; }

export default function UploadPage() {
  const [file, setFile] = useState(null); const [duplicate, setDuplicate] = useState(null); const [documentInfo, setDocumentInfo] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(''); const [feedback, setFeedback] = useState(null); const router = useRouter();
  const pick = event => { setFile(event.target.files?.[0] || null); setDocumentInfo(null); setDuplicate(null); setError(''); };
  function removeFile() { setFile(null); setDocumentInfo(null); setDuplicate(null); }
  async function upload() { const form = document.querySelector('#meta-form'); if (!file || !form.reportValidity()) return; setLoading('upload'); setError(''); try { const data = new FormData(form); data.append('file', file); setDocumentInfo(await request('/api/documents/upload', {method:'POST', body:data})); setFeedback({tone:'success', message:'Document uploaded. You can now check it and submit it for review.'}); } catch { setError('We could not upload this document. Check the file and required location details, then try again.'); } finally { setLoading(''); } }
  async function check() { if (!documentInfo) return; setLoading('check'); setError(''); try { setDuplicate(await request(`/api/documents/${documentInfo.document_id}/duplicate-check`, {method:'POST'})); } catch { setError('We could not check this document right now. Please try again.'); } finally { setLoading(''); } }
  async function submit() { if (!documentInfo) return; setLoading('submit'); setError(''); try { await request(`/api/documents/${documentInfo.document_id}/submit`, {method:'POST'}); router.push('/user/submissions?submitted=1'); } catch { setError('We could not submit this document for review. Please try again.'); } finally { setLoading(''); } }
  return <>
    <div className="page-title citizen-page-title"><div><div className="eyebrow">NEW SUBMISSION</div><h2>Upload a land record</h2><p>Share a scanned or photographed document for officer verification.</p></div></div>
    <Journey uploaded={Boolean(documentInfo)}/><ErrorMessage>{error}</ErrorMessage><Toast message={feedback?.message} tone={feedback?.tone} onDismiss={() => setFeedback(null)}/>
    <div className="split upload-layout citizen-upload-layout"><section className="card upload-card source-upload-card"><div className="section-head"><div><div className="eyebrow">STEP 1</div><h3>Select a document</h3><p>JPG, JPEG, PNG, or PDF. Choose a complete, legible record.</p></div></div><label className="dropzone citizen-dropzone"><UploadCloud size={35}/><h3>{file ? 'Choose a different document' : 'Drop a land record here'}</h3><p>Or click to browse files from your device.</p><span className="button secondary">Browse files</span><input onChange={pick} type="file" accept="image/jpeg,image/png,.pdf" disabled={Boolean(loading)}/></label>{file && <div className="file-preview"><div className="file-preview-icon">{file.type.startsWith('image/') ? <FileImage size={27}/> : <FileText size={27}/>}</div><div><b>{file.name}</b><small>{file.type || 'Document'} · {(file.size / 1024 / 1024).toFixed(2)} MB</small></div><button className="button secondary" onClick={removeFile} disabled={Boolean(loading)}><X size={15}/> Remove</button></div>}</section>
      <section className="card upload-card citizen-metadata-card"><div className="section-head"><div><div className="eyebrow">STEP 2</div><h3>Document location</h3><p>These details help identify the record during review.</p></div></div><form id="meta-form" className="form-grid"><div className="field"><label>State</label><input name="state" required/></div><div className="field"><label>District</label><input name="district" required/></div><div className="field"><label>Tehsil</label><input name="tehsil" required/></div><div className="field"><label>Village</label><input name="village" required/></div><div className="field full"><label>Document type</label><select name="document_type" required><option value="">Select type</option>{['Khatauni','Khasra','Jamabandi','Record of Rights','Registry','Other'].map(type => <option key={type}>{type}</option>)}</select></div></form></section></div>
    <section className="card submission-actions-card citizen-upload-actions"><div className="section-head"><div><div className="eyebrow">NEXT STEP</div><h3>Submit for verification</h3><p>{documentInfo ? 'Your document is uploaded. Check it if needed, then send it to the officer review queue.' : 'Select a document and complete the location details to upload it.'}</p></div><div className="actions"><Button onClick={upload} loading={loading === 'upload'} loadingText="Uploading…" disabled={!file || Boolean(loading)}><UploadCloud size={15}/> Upload document</Button><Button variant="secondary" onClick={check} loading={loading === 'check'} loadingText="Checking…" disabled={!documentInfo || Boolean(loading)}><Search size={15}/> Check document</Button><Button onClick={submit} loading={loading === 'submit'} loadingText="Submitting…" disabled={!documentInfo || Boolean(loading)}><Send size={15}/> Submit for review</Button></div></div>{duplicate && <div className={`notice ${duplicate.duplicate ? 'warn' : 'success'}`} role="status">{duplicate.message} This check supports review and does not make a decision automatically.</div>}</section>
  </>;
}
