'use client';

import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {UploadCloud, FileImage, X, Search, Send} from 'lucide-react';
import {request} from '../../../lib/api';
import {Button, ErrorMessage} from '../../../components/common/UI';

export default function UploadPage() {
  const [file, setFile] = useState(null); const [duplicate, setDuplicate] = useState(null); const [documentInfo, setDocumentInfo] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(''); const router = useRouter();
  const pick = event => { setFile(event.target.files?.[0]); setDocumentInfo(null); setDuplicate(null); };
  async function upload() { const form = document.querySelector('#meta-form'); if (!file || !form.reportValidity()) return; setLoading('upload'); try { const data = new FormData(form); data.append('file', file); setDocumentInfo(await request('/api/documents/upload', {method:'POST', body:data})); } catch (err) { setError(err.message); } finally { setLoading(''); } }
  async function check() { if (!documentInfo) return; setLoading('check'); try { setDuplicate(await request(`/api/documents/${documentInfo.document_id}/duplicate-check`, {method:'POST'})); } catch (err) { setError(err.message); } finally { setLoading(''); } }
  async function submit() { if (!documentInfo) return; setLoading('submit'); try { await request(`/api/documents/${documentInfo.document_id}/submit`, {method:'POST'}); router.push('/user/submissions?submitted=1'); } catch (err) { setError(err.message); } finally { setLoading(''); } }
  return <><div className="page-title"><div><div className="eyebrow">NEW SUBMISSION</div><h2>Upload Land Record</h2><p>Upload a scanned or photographed record for officer verification.</p></div></div><ErrorMessage>{error}</ErrorMessage><div className="split upload-layout"><section className="card upload-card source-upload-card"><label className="dropzone"><UploadCloud size={35}/><h3>Drop a land record here</h3><span className="button secondary">Choose file</span><input onChange={pick} type="file" accept="image/jpeg,image/png,.pdf"/></label>{file && <div className="file-preview">{file.type.startsWith('image/') ? <img src={URL.createObjectURL(file)} alt="Preview"/> : <FileImage size={38}/>}<div><b>{file.name}</b><small>{(file.size / 1024 / 1024).toFixed(2)} MB</small></div><button className="button secondary" onClick={() => setFile(null)}><X size={15}/> Remove</button></div>}</section><section className="card upload-card"><form id="meta-form" className="form-grid"><div className="field"><label>State</label><input name="state" required/></div><div className="field"><label>District</label><input name="district" required/></div><div className="field"><label>Tehsil</label><input name="tehsil" required/></div><div className="field"><label>Village</label><input name="village" required/></div><div className="field full"><label>Document type</label><select name="document_type" required><option value="">Select type</option>{['Khatauni','Khasra','Jamabandi','Record of Rights','Registry','Other'].map(type => <option key={type}>{type}</option>)}</select></div></form></section></div><section className="card submission-actions-card"><div className="actions"><Button onClick={upload} loading={loading === 'upload'} disabled={!file}>Upload document</Button><Button variant="secondary" onClick={check} loading={loading === 'check'} disabled={!documentInfo}><Search size={15}/> Check duplicate</Button><Button onClick={submit} loading={loading === 'submit'} disabled={!documentInfo}><Send size={15}/> Submit to officer</Button></div>{duplicate && <div className={`notice ${duplicate.duplicate ? 'warn' : 'success'}`}>{duplicate.message} Duplicate checking is decision support only.</div>}</section></>;
}
