from datetime import datetime
from sqlalchemy import String, Text, DateTime, Float, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .database import Base
class User(Base):
    __tablename__='users'; id: Mapped[int]=mapped_column(primary_key=True); username: Mapped[str]=mapped_column(String,unique=True); password: Mapped[str]=mapped_column(String); role: Mapped[str]=mapped_column(String)
class Document(Base):
    __tablename__='documents'; id: Mapped[int]=mapped_column(primary_key=True); record_id: Mapped[str]=mapped_column(String,unique=True); original_name: Mapped[str]=mapped_column(String); stored_path: Mapped[str]=mapped_column(String); enhanced_path: Mapped[str|None]=mapped_column(String,nullable=True); sha256: Mapped[str]=mapped_column(String,index=True); uploader_id: Mapped[int]=mapped_column(ForeignKey('users.id')); status: Mapped[str]=mapped_column(String,default='UPLOADED'); metadata_json: Mapped[str]=mapped_column(Text,default='{}'); raw_ocr: Mapped[str|None]=mapped_column(Text,nullable=True); ocr_engine: Mapped[str|None]=mapped_column(String,nullable=True); ocr_status: Mapped[str]=mapped_column(String,default='NOT_RUN'); created_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); verified_at: Mapped[datetime|None]=mapped_column(DateTime,nullable=True); officer_id: Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); fields: Mapped[list['Field']]=relationship(cascade='all, delete-orphan')
class Field(Base):
    __tablename__='fields'; id: Mapped[int]=mapped_column(primary_key=True); document_id: Mapped[int]=mapped_column(ForeignKey('documents.id')); field_name: Mapped[str]=mapped_column(String); ai_value: Mapped[str|None]=mapped_column(Text,nullable=True); ai_confidence: Mapped[float|None]=mapped_column(Float,nullable=True); officer_value: Mapped[str|None]=mapped_column(Text,nullable=True); final_value: Mapped[str|None]=mapped_column(Text,nullable=True); edited_by: Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); edited_at: Mapped[datetime|None]=mapped_column(DateTime,nullable=True); edit_reason: Mapped[str|None]=mapped_column(Text,nullable=True)
class Audit(Base):
    __tablename__='audit_logs'; id: Mapped[int]=mapped_column(primary_key=True); document_id: Mapped[int|None]=mapped_column(ForeignKey('documents.id'),nullable=True); actor: Mapped[str]=mapped_column(String); role: Mapped[str]=mapped_column(String); action: Mapped[str]=mapped_column(String); old_value: Mapped[str|None]=mapped_column(Text,nullable=True); new_value: Mapped[str|None]=mapped_column(Text,nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
