'use client';

import {useEffect, useState} from 'react';
import {api} from '../../../lib/api';
import {Button, ErrorMessage, Loader} from '../../../components/common/UI';

export default function ProfilePage() {
  const [profile, setProfile] = useState(null); const [code, setCode] = useState(''); const [emailDelivery, setEmailDelivery] = useState(null); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { api.me().then(setProfile).catch(err => setError(err.message)); }, []);
  async function save(event) { event.preventDefault(); setError(''); try { const data = Object.fromEntries(new FormData(event.currentTarget)); const updated = await api.updateProfile(data); setProfile(updated); setMessage('Profile completed. Email verification remains optional.'); } catch (err) { setError(err.message); } }
  async function requestEmail() { try { setEmailDelivery(await api.requestEmailVerification()); } catch (err) { setError(err.message); } }
  async function verifyEmail() { try { await api.verifyEmail(code); setProfile(await api.me()); setEmailDelivery(null); setMessage('Email verified.'); } catch (err) { setError(err.message); } }
  if (!profile) return <Loader label="Loading profile…"/>;
  return <><div className="page-title"><div><div className="eyebrow">CITIZEN IDENTITY</div><h2>Profile & verification</h2><p>Phone verification is required. Email verification is optional.</p></div></div><ErrorMessage>{error}</ErrorMessage>{message && <div className="notice success">{message}</div>}<section className="card"><form className="form-grid" onSubmit={save}><div className="field"><label>Full name</label><input name="name" defaultValue={profile.name || ''} required/></div><div className="field"><label>Verified phone</label><input value={profile.phone_number || 'Not verified'} disabled/></div><div className="field"><label>Email address</label><input name="email" type="email" defaultValue={profile.email || ''} required/></div><div className="field"><label>Email status</label><input value={profile.email_verified ? 'Verified' : 'Not verified — optional'} disabled/></div><div className="field"><label>State</label><input name="state" defaultValue={profile.state || ''} required/></div><div className="field"><label>District</label><input name="district" defaultValue={profile.district || ''} required/></div><div className="field"><label>Pincode (optional)</label><input name="pincode" defaultValue={profile.pincode || ''}/></div><div className="field"><label>Aadhaar (optional)</label><input name="aadhaar_number" inputMode="numeric" placeholder={profile.aadhaar_masked || '12 digits'} maxLength={14}/><small>{profile.aadhaar_provided ? `${profile.aadhaar_masked} — Provided, Unverified` : 'Provided Aadhaar is never UIDAI verified here.'}</small></div><div className="field full"><label>Address (optional)</label><textarea name="address" defaultValue={profile.address || ''} maxLength={500}/></div><div className="actions"><Button>Save profile</Button>{!profile.email_verified && <Button type="button" variant="secondary" onClick={requestEmail}>Verify Email</Button>}</div></form>{emailDelivery && <div className="notice"><b>{emailDelivery.message}</b>{emailDelivery.development_code && <><br/>Development code: <b>{emailDelivery.development_code}</b></>}<div className="actions"><input value={code} onChange={event => setCode(event.target.value.replace(/\D/g, '').slice(0, 6))} placeholder="6-digit code"/><Button onClick={verifyEmail} disabled={code.length !== 6}>Confirm email</Button></div></div>}</section></>;
}
