'use client';

import {useEffect, useState} from 'react';
import {BadgeCheck, MailCheck, ShieldCheck} from 'lucide-react';
import {api} from '../../../lib/api';
import {Button, ErrorMessage, Loader, Toast} from '../../../components/common/UI';

export default function ProfilePage() {
  const [profile, setProfile] = useState(null); const [code, setCode] = useState(''); const [emailDelivery, setEmailDelivery] = useState(null); const [feedback, setFeedback] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState('');
  useEffect(() => { api.me().then(setProfile).catch(() => setError('We could not load your profile. Please try again.')); }, []);
  async function save(event) { event.preventDefault(); setLoading('save'); setError(''); try { const data = Object.fromEntries(new FormData(event.currentTarget)); const updated = await api.updateProfile(data); setProfile(updated); setFeedback({tone:'success', message:'Profile saved. Email verification remains optional.'}); } catch { setError('We could not save your profile. Check the highlighted details and try again.'); } finally { setLoading(''); } }
  async function requestEmail() { setLoading('email'); setError(''); try { setEmailDelivery(await api.requestEmailVerification()); } catch { setError('We could not send an email verification code. Please try again.'); } finally { setLoading(''); } }
  async function verifyEmail() { setLoading('verify'); setError(''); try { await api.verifyEmail(code); setProfile(await api.me()); setEmailDelivery(null); setFeedback({tone:'success', message:'Email verified.'}); } catch { setError('That verification code could not be confirmed. Please try again.'); } finally { setLoading(''); } }
  if (!profile) return error ? <ErrorMessage>{error}</ErrorMessage> : <Loader label="Loading your profile…"/>;
  return <>
    <div className="page-title citizen-page-title"><div><div className="eyebrow">CITIZEN IDENTITY</div><h2>Profile & verification</h2><p>Keep your contact and location details current for submitted records.</p></div></div>
    <ErrorMessage>{error}</ErrorMessage><Toast message={feedback?.message} tone={feedback?.tone} onDismiss={() => setFeedback(null)}/>
    <section className="profile-status-grid"><div className="profile-status-card verified"><BadgeCheck size={19}/><div><b>Phone verified</b><span>{profile.phone_number || 'Verified phone number'}</span></div></div><div className={`profile-status-card ${profile.email_verified ? 'verified' : ''}`}><MailCheck size={19}/><div><b>{profile.email_verified ? 'Email verified' : 'Email verification optional'}</b><span>{profile.email || 'Add an email address to verify it.'}</span></div></div><div className="profile-status-card"><ShieldCheck size={19}/><div><b>Your profile is private</b><span>Only the details needed for record handling are shown here.</span></div></div></section>
    <section className="card citizen-profile-card"><form className="form-grid" onSubmit={save}><div className="profile-form-heading"><div className="eyebrow">PROFILE DETAILS</div><h3>Contact and location</h3><p>Required fields help officers identify your submitted records.</p></div><div className="field"><label>Full name</label><input name="name" defaultValue={profile.name || ''} required/></div><div className="field"><label>Verified phone</label><input value={profile.phone_number || 'Not verified'} disabled/></div><div className="field"><label>Email address</label><input name="email" type="email" defaultValue={profile.email || ''} required/></div><div className="field"><label>Email status</label><input value={profile.email_verified ? 'Verified' : 'Not verified — optional'} disabled/></div><div className="field"><label>State</label><input name="state" defaultValue={profile.state || ''} required/></div><div className="field"><label>District</label><input name="district" defaultValue={profile.district || ''} required/></div><div className="field"><label>Pincode (optional)</label><input name="pincode" defaultValue={profile.pincode || ''}/></div><div className="field"><label>Aadhaar (optional)</label><input name="aadhaar_number" inputMode="numeric" placeholder={profile.aadhaar_masked || '12 digits'} maxLength={14}/><small>{profile.aadhaar_provided ? `${profile.aadhaar_masked} — Provided, unverified` : 'Provided Aadhaar is not verified here.'}</small></div><div className="field full"><label>Address (optional)</label><textarea name="address" defaultValue={profile.address || ''} maxLength={500}/></div><div className="actions profile-actions"><Button loading={loading === 'save'} loadingText="Saving…" disabled={Boolean(loading)}>Save profile</Button>{!profile.email_verified && <Button type="button" variant="secondary" onClick={requestEmail} loading={loading === 'email'} loadingText="Sending…" disabled={Boolean(loading)}>Verify email</Button>}</div></form>{emailDelivery && <div className="notice profile-verification"><b>{emailDelivery.message}</b>{emailDelivery.development_code && <><br/>Development code: <b>{emailDelivery.development_code}</b></>}<div className="actions"><input value={code} onChange={event => setCode(event.target.value.replace(/\D/g, '').slice(0, 6))} placeholder="6-digit code" inputMode="numeric"/><Button onClick={verifyEmail} loading={loading === 'verify'} loadingText="Confirming…" disabled={code.length !== 6 || Boolean(loading)}>Confirm email</Button></div></div>}</section>
  </>;
}
