const BILINGUAL_LABELS = {
  'जनपद': 'जनपद / District',
  'तहसील': 'तहसील / Tehsil',
  'राजस्व ग्राम': 'राजस्व ग्राम / Revenue Village',
  'ग्राम का नाम': 'ग्राम का नाम / Village Name',
  'ग्राम कोड': 'ग्राम कोड / Village Code',
  'परगना': 'परगना / Pargana',
  'फसली वर्ष': 'फसली वर्ष / Fasli Year',
  'खाता संख्या': 'खाता संख्या / Khata Number',
  'खातेदार का नाम': 'खातेदार का नाम / Khatedar Name',
  'पिता / पति का नाम': 'पिता / पति का नाम / Father / Husband Name',
  'पटवारी हल्का': 'पटवारी हल्का / Patwari Halka',
  'पटवारी का नाम': 'पटवारी का नाम / Patwari Name',
  'लेखपाल का नाम': 'लेखपाल का नाम / Lekhpal Name',
  'निर्गमन तिथि': 'निर्गमन तिथि / Issue Date',
  'क्रम संख्या': 'क्रम संख्या / Serial Number',
  'गाटा संख्या': 'गाटा संख्या / Gata Number',
  'खसरा संख्या': 'खसरा संख्या / Khasra Number',
  'गाटा / खसरा संख्या': 'गाटा / खसरा संख्या / Gata / Khasra Number',
  'खातेदार / भूमिधर का नाम': 'खातेदार / भूमिधर का नाम / Khatedar / Bhumidhar Name',
  'पिता / पति / संरक्षक का नाम': 'पिता / पति / संरक्षक का नाम / Father / Husband / Guardian Name',
  'निवास स्थान': 'निवास स्थान / Residence',
  'हिस्सा': 'हिस्सा / Ownership Share',
  'खातेदार का अंश': 'खातेदार का अंश / Ownership Share',
  'क्षेत्रफल / रकबा': 'क्षेत्रफल / रकबा / Land Area',
  'भूमि का क्षेत्रफल': 'भूमि का क्षेत्रफल / Land Area',
  'भूमि का प्रकार': 'भूमि का प्रकार / Land Type',
  'सिंचाई का साधन': 'सिंचाई का साधन / Irrigation Source',
  'लगान': 'लगान / Land Revenue',
  'भूमि की श्रेणी': 'भूमि की श्रेणी / Land Category',
  'आदेश / परिवर्तन विवरण / टिप्पणी': 'आदेश / परिवर्तन विवरण / टिप्पणी / Order / Mutation Details / Remarks',
  'मुख्य खतौनी तालिका': 'मुख्य खतौनी तालिका / Main Khatauni Table',
};

export const bilingualKhatauniLabel = (label) => BILINGUAL_LABELS[label] || label;
